name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client and rsync
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openssh-client rsync

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_EC2 }}" > ~/.ssh/ssh-key.pem
          chmod 400 ~/.ssh/ssh-key.pem
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          
      - name: Test connection to EC2
        run: |
          ssh -i ~/.ssh/ssh-key.pem ubuntu@${{ secrets.EC2_ADDRESS }} "echo 'Connection successful!'"
          
      - name: Create logs directory on EC2
        run: |
          ssh -i ~/.ssh/ssh-key.pem ubuntu@${{ secrets.EC2_ADDRESS }} 'mkdir -p air-quality-pipeline/logs'  

      - name: Deploy code to EC2
        run: |
          ssh -T -i ~/.ssh/ssh-key.pem ubuntu@${{ secrets.EC2_ADDRESS }} '
            set -x;  # Enable debugging
            if [ -d air-quality-pipeline ]; 
            then 
              cd air-quality-pipeline &&
              pwd;  # Print current working directory
              git status &&
              git pull --rebase &&
              git status;
            else
              git config --global --replace-all user.name "Aniq Premji" &&
              git config --global --replace-all user.email ${{ secrets.EMAIL }};
              git clone https://github.com/aniqp/air-quality-pipeline.git &&
              cd air-quality-pipeline &&
              ls -la &&
              chmod 777 logs &&
              cd docker/airflow &&
              docker-compose up airflow-init; 
            fi'

          ssh -T -i ~/.ssh/ssh-key.pem ubuntu@${{ secrets.EC2_ADDRESS }} '
            cd air-quality-pipeline/docker/airflow && 
            pwd;  # Print current working directory
            if docker ps | grep -q keyword; 
            then docker-compose down && docker-compose up -d --build; 
            else docker-compose up -d --build; 
            fi;'
